### ISSUE TITLE
Not playing any rtsp stream

### ISSUE THREAD

**Issue by Jagdeep-Sing** [kuyen/android-play-rtsp-by-videoview#1]
Hey thanks for this demo but why its not playing any rtsp stream. the default URL its also not playing and shows a msg "cannot play video"

**Comment by iamcxa** [comment]
@Jagdeep-Sing hi seems like the default URL is dead.

can you please try this one: rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov 

which comes from here: https://www.wowza.com/demo/rtsp
